# ML lab3
### Jwalit Shah - CE121 

done in colab

In [2]:
# Importing Libraries
import numpy as np
import io
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import datasets, preprocessing
from sklearn.naive_bayes import GaussianNB, MultinomialNB

In [3]:
from google.colab import files
uploaded = files.upload()

# Loading dataset
dataset = pd.read_csv(io.BytesIO(uploaded['Dataset1.csv']))

Saving Dataset1.csv to Dataset1.csv


## Preprocessing

In [4]:
le = preprocessing.LabelEncoder()

print(dataset)
# Generate dummies for column Outlook
dummy_outlook = pd.get_dummies(dataset['Outlook'])
dataset = dataset.drop(['Outlook'],axis=1)
dataset = pd.concat([dummy_outlook,dataset],axis=1)
# print(dummy_outlook)

# Generate dummies for column Outlook
dummy_wind = pd.get_dummies(dataset['Wind'])
dataset = dataset.drop(['Wind'],axis=1)
dataset = pd.concat([dummy_wind,dataset],axis=1)

# Use label encoder for columns Temp,Humidity and label Play
dataset['Temp'] = le.fit_transform(dataset['Temp'])
dataset['Humidity'] = le.fit_transform(dataset['Humidity'])
dataset['Play'] = le.fit_transform(dataset['Play'])


print(dataset)

   Outlook Temp Humidity Wind Play
0        R    H   Normal    F    N
1        R    H     High    T    N
2        O    H   Normal    F    Y
3        S    M   Normal    F    Y
4        S    C   Normal    F    Y
5        S    C      Low    T    N
6        O    C   Normal    T    Y
7        R    M   Normal    F    N
8        R    C      Low    F    Y
9        S    M     High    F    Y
10       R    M     High    T    Y
11       O    M      Low    T    Y
12       O    H   Normal    F    Y
13       S    M   Normal    T    N
    F  T  O  R  S  Temp  Humidity  Play
0   1  0  0  1  0     1         2     0
1   0  1  0  1  0     1         0     0
2   1  0  1  0  0     1         2     1
3   1  0  0  0  1     2         2     1
4   1  0  0  0  1     0         2     1
5   0  1  0  0  1     0         1     0
6   0  1  1  0  0     0         2     1
7   1  0  0  1  0     2         2     0
8   1  0  0  1  0     0         1     1
9   1  0  0  0  1     2         0     1
10  0  1  0  1  0     2         0  

In [5]:
X = dataset.iloc[:,:7].values
Y = dataset.iloc[:,7].values
print(X)
print(Y)

[[1 0 0 1 0 1 2]
 [0 1 0 1 0 1 0]
 [1 0 1 0 0 1 2]
 [1 0 0 0 1 2 2]
 [1 0 0 0 1 0 2]
 [0 1 0 0 1 0 1]
 [0 1 1 0 0 0 2]
 [1 0 0 1 0 2 2]
 [1 0 0 1 0 0 1]
 [1 0 0 0 1 2 0]
 [0 1 0 1 0 2 0]
 [0 1 1 0 0 2 1]
 [1 0 1 0 0 1 2]
 [0 1 0 0 1 2 2]]
[0 0 1 1 1 0 1 0 1 1 1 1 1 0]


In [6]:
from sklearn.model_selection import train_test_split

# Splitting dataset
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.30, random_state = 56)

## Train model using Naive Bayes classifier

In [7]:
model=MultinomialNB()

# Train the model using the training sets
model.fit(X_train,Y_train)

# predict test data
Y_pred = model.predict(X_test)

print(Y_test)
print(Y_pred)

[1 1 0 1 1]
[0 1 0 1 0]


In [8]:
from sklearn import metrics

print(f"Accuracy is :- {metrics.accuracy_score(Y_test, Y_pred)}")

# print precision and recall
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score

precision = precision_score(Y_test, Y_pred)
recall = recall_score(Y_test, Y_pred)

print(f"precision :- {precision}")
print(f"recall :- {recall}")

Accuracy is :- 0.6
precision :- 1.0
recall :- 0.5
