# ML lab3
### Jwalit Shah - CE121 

done in colab

In [1]:
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive


In [2]:
# Importing Libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import datasets, preprocessing
from sklearn.naive_bayes import GaussianNB, MultinomialNB

In [38]:
# Loading dataset
dataset = pd.read_csv("/content/drive/MyDrive/My_Sem_7/ML_Lab/Lab3/Dataset1.csv")

## Preprocessing

In [39]:
le = preprocessing.LabelEncoder()

# Generate dummies for column Outlook
dummy_outlook = pd.get_dummies(dataset['Outlook'])
dataset = dataset.drop(['Outlook'],axis=1)
dataset = pd.concat([dummy_outlook,dataset],axis=1)
# print(dummy_outlook)

# Generate dummies for column Outlook
dummy_wind = pd.get_dummies(dataset['Wind'])
dataset = dataset.drop(['Wind'],axis=1)
dataset = pd.concat([dummy_wind,dataset],axis=1)

# Use label encoder for columns Temp,Humidity and label Play
dataset['Temp'] = le.fit_transform(dataset['Temp'])
dataset['Humidity'] = le.fit_transform(dataset['Humidity'])
dataset['Play'] = le.fit_transform(dataset['Play'])


print(dataset)

    F  T  O  R  S  Temp  Humidity  Play
0   1  0  0  1  0     1         2     0
1   0  1  0  1  0     1         0     0
2   1  0  1  0  0     1         2     1
3   1  0  0  0  1     2         2     1
4   1  0  0  0  1     0         2     1
5   0  1  0  0  1     0         1     0
6   0  1  1  0  0     0         2     1
7   1  0  0  1  0     2         2     0
8   1  0  0  1  0     0         1     1
9   1  0  0  0  1     2         0     1
10  0  1  0  1  0     2         0     1
11  0  1  1  0  0     2         1     1
12  1  0  1  0  0     1         2     1
13  0  1  0  0  1     2         2     0


In [40]:
X = dataset.iloc[:,:7].values
Y = dataset.iloc[:,7].values
print(X)
print(Y)

[[1 0 0 1 0 1 2]
 [0 1 0 1 0 1 0]
 [1 0 1 0 0 1 2]
 [1 0 0 0 1 2 2]
 [1 0 0 0 1 0 2]
 [0 1 0 0 1 0 1]
 [0 1 1 0 0 0 2]
 [1 0 0 1 0 2 2]
 [1 0 0 1 0 0 1]
 [1 0 0 0 1 2 0]
 [0 1 0 1 0 2 0]
 [0 1 1 0 0 2 1]
 [1 0 1 0 0 1 2]
 [0 1 0 0 1 2 2]]
[0 0 1 1 1 0 1 0 1 1 1 1 1 0]


In [43]:
from sklearn.model_selection import train_test_split

# Splitting dataset
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.30, random_state = 56)

## Train model using Naive Bayes classifier

In [44]:
model=MultinomialNB()

# Train the model using the training sets
model.fit(X_train,Y_train)

# predict test data
Y_pred = model.predict(X_test)

print(Y_test)
print(Y_pred)

[1 1 0 1 1]
[0 1 0 1 0]


In [45]:
from sklearn import metrics

print(f"Accuracy is :- {metrics.accuracy_score(Y_test, Y_pred)}")

# print precision and recall
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score

precision = precision_score(Y_test, Y_pred)
recall = recall_score(Y_test, Y_pred)

print(f"precision :- {precision}")
print(f"recall :- {recall}")

Accuracy is :- 0.6
precision :- 1.0
recall :- 0.5
